apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "kubeclust"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "kubeclust"
    spec:
      containers:
        - name: "kubeclust"
          image: "evilacr.azurecr.io/kubeclust"
          ports:
          - containerPort: 80